## https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/README.md
## https://artifacthub.io/packages/helm/metrics-server/metrics-server
metrics-server:
  enabled: true
  args: [
    # not recommended in production
    --kubelet-insecure-tls,
    --kubelet-preferred-address-types=InternalIP
  ]

# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md
# https://artifacthub.io/packages/helm/prometheus-community/prometheus
prometheus:
  enabled: true
  extraScrapeConfigs: |
    - job_name: 'ingress-nginx'
      metrics_path: /metrics
      scrape_interval: 5s
      static_configs:
        - targets:
          - {{ .Release.Name }}-ingress-nginx-controller-metrics:10254
  nodeExporter:
    hostRootfs: false

# https://github.com/kubernetes-sigs/service-catalog/blob/master/charts/catalog/README.md
catalog:
  enabled: false

# https://kubernetes.github.io/ingress-nginx/
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
ingress-nginx:
  enabled: true
  controller:
    metrics:
      enabled: true
    ingressClassResource:
      default: true

# https://github.com/jetstack/cert-manager/blob/master/README.md
# https://artifacthub.io/packages/helm/jetstack/cert-manager
cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false

# https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md
# https://artifacthub.io/packages/helm/grafana/grafana
grafana:
  enabled: true
  dashboards:
    default:
      k8s-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      k8s-cluster-metrics:
        gnetId: 11663
        revision: 1
        datasource: Prometheus
      k8s-cluster-metrics-simple:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
      k8s-pods-monitoring:
        gnetId: 13498
        revision: 1
        datasource: Prometheus
      k8s-memory:
        gnetId: 13421
        revision: 1
        datasource: Prometheus
      k8s-networking:
        gnetId: 12658
        revision: 1
        datasource: Prometheus
      k8s-pods:
        gnetId: 6336
        revision: 1
        datasource: Prometheus
      spring-boot:
        gnetId: 12464
        revision: 2
        datasource: Prometheus
      nginx-ingress-controller:
        gnetId: 9614
        revision: 1
        datasource: Prometheus
      oci-compute:
        gnetId: 13596
        revision: 1
        datasource: Oracle Cloud Infrastructure Metrics
      oci-oke:
        gnetId: 13594
        revision: 1
        datasource: Oracle Cloud Infrastructure Metrics
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
    dashboards:
      enabled: true
      label: grafana_dashboard
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true
  persistence:
    enabled: true
  plugins:
    - oci-logs-datasource
    - oci-metrics-datasource
    - grafana-kubernetes-app
    - grafana-worldmap-panel
    - grafana-piechart-panel
    - btplc-status-dot-panel

# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md
jenkins:
  enabled: false
  #https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
  controller:
    serviceType: ClusterIP
    jenkinsUriPrefix: "/jenkins"
    ingress:
      # enable ingress only if the ingress-controller `nginx-ingress` is enabled.
      enabled: true
      apiVersion: networking.k8s.io/v1
      metadata:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      labels: {}
      spec:
        ingressClassName: nginx
        rules:
        - http:
            paths:
              - path: /jenkins(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: mushop-setup-jenkins
                    port: 
                      number: 8080
    installPlugins:
        - kubernetes:3900.va_dce992317b_4
        - workflow-aggregator:596.v8c21c963d92d
        - git:5.0.1
        - configuration-as-code:1625.v27444588cc3d
        - blueocean:1.27.3
        - credentials-binding:604.vb_64480b_c56ca_
        - workflow-job:1292.v27d8cc3e2602

