apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mushop-dev
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: edge
          servicePort: 80