apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mushop-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
spec:
  ingressClassName: nginx
  tls:
  - secretName: mushop-prod-tls
    hosts:
    - mushop.ateam.cloud
    - insecure.mushop.ateam.cloud
  rules:
  - host: mushop.ateam.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: edge
          servicePort: 80
  - host: insecure.mushop.ateam.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: edge
          servicePort: 80