{{- range .Values.global.services }}
{{- $svcName := . }}
{{/* The svcKey has the value of e.g. .Values.catalogue. This is so we can use it to check if we need to overwrite the values*/}}
{{- $svcKey := index $.Values (printf "%s" $svcName) -}}
{{- $svcOsbKey := index $.Values (printf "%s.osb" $svcName) -}}

{{- $name := $svcKey.secrets.oadbName | default (printf "mu%s%s" $svcName (randAlphaNum 12)) | trunc 14 }}
{{- $user := $svcKey.secrets.oadbUser | default (printf "user%s" (randAlphaNum 12)) }}
{{- $pass := $svcKey.secrets.oadbPassword | default (printf "%s%s" (randAlpha 1) (randAlphaNum 12)) }}
{{- $wpass := $svcKey.secrets.oadbWalletPassword | default (randAlphaNum 12) }}

{{/* Check if need to create ATP secrets for the particular service */}}
{{ if $svcOsbKey.atp -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svcName }}-oadb-admin
  labels:
{{ include "provision.labels" . | indent 4 }}
type: Opaque
data:
  {{- $pass := $svcKey.oadbAdminPassword | default (randAlphaNum 30) }}
  oadb_admin_pw: {{ $pass | b64enc }}
  oadb_admin_pw_osb: {{ printf `{"password":"%s"}` $pass | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svcName }}-oadb-connection
  labels:
{{ include "provision.labels" . | indent 4 }}
type: Opaque
data:
  oadb_db: {{ $name | b64enc }}
  oadb_db_osb: {{ printf `{"dbName":"%s"}` $name | b64enc }}
  oadb_service: {{ printf "%s_tp" $name | lower | b64enc }}
  oadb_wallet_pw: {{ $wpass | b64enc }}
  oadb_wallet_pw_osb: {{ printf `{"walletPassword":"%s"}` $wpass | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svcName }}-oadb-credentials
  labels:
{{ include "provision.labels" . | indent 4 }}
type: Opaque
data:
  oadb_user: {{ $user | b64enc }}
  oadb_pw: {{ $pass | b64enc }}
{{- end }}
{{- end }}
