micronaut:
  application:
    name: fulfillment
  server:
    port: 80
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    binders:
      jvm:
        enabled: true
      web:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true



endpoints:
    prometheus:
        enabled: true
        sensitive: false

        

mushop:
  messaging:
    host: ${nats.host:localhost}
    port: ${nats.port:4222}
    simulation-delay: ${simulation.delay:8000}
    subjects:
      orders: ${orders.new:mushop-orders}
      shipments: ${orders.shipped:mushop-shipments}
