apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    name: carts
    app.kubernetes.io/name: carts
  spec:
    selector:
      name: carts
      app.kubernetes.io/name: carts
    ports:
      - port: 80
        name: http
        targetPort: 80
    