---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
    app.kubernetes.io/name: catalogue
  spec:
    selector:
      name: catalogue
      app.kubernetes.io/name: catalogue
    ports:
      - port: 80
        name: http
        targetPort: 80
