---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
    app.kubernetes.io/name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
      app.kubernetes.io/name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: catalogue
          image: iad.ocir.io/oracle/ateam/mushop-catalogue:1.4
          imagePullPolicy: Always
          command: ["/app/catalogue"]
          args:
          - -port=8080
          ports:
            - name: http
              containerPort: 8080
          env:
          - name: ZIPKIN
            value:
          - name: OADB_USER
            valueFrom:
              secretKeyRef:
                name: catalogue-oadb-credentials
                key: oadb_user
          - name: OADB_PW
            valueFrom:
              secretKeyRef:
                name: catalogue-oadb-credentials
                key: oadb_pw
          - name: OADB_SERVICE
            valueFrom:
              secretKeyRef:
                name: catalogue-oadb-connection
                key: oadb_service
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
          - name: wallet
            mountPath: "/usr/lib/oracle/19.10/client64/lib/network/admin"
      volumes:
      - name: wallet
        secret:
          secretName: catalogue-oadb-wallet
          defaultMode: 256