---
apiVersion: v1
kind: Service
metadata:
  name: edge
  labels:
    name: edge
    layer: client
    app.kubernetes.io/name: edge
spec:
  selector:
    name: edge
    layer: client
    app.kubernetes.io/name: edge
  ports:
    - port: 80
      name: http
      targetPort: 8080