---
apiVersion: v1
kind: Service
metadata:
  name: events
  labels:
    app.kubernetes.io/name: events
spec:
  selector:
    app.kubernetes.io/name: events
  ports:
    - port: 80
      name: http
      targetPort: 8080
