---
apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  labels: 
    app.kubernetes.io/name: fulfillment
    run: fulfillment
spec:
  selector:
    app.kubernetes.io/name: fulfillment
    run: fulfillment
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
