apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
    app.kubernetes.io/name: orders
spec:
  selector:
    name: orders
    app.kubernetes.io/name: orders
  ports:
    - port: 80
      name: http
      targetPort: 80
