---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    name: payment
    app.kubernetes.io/name: payment
spec:
  selector:
    name: payment
    app.kubernetes.io/name: payment
  ports:
    - port: 80
      name: http
      targetPort: 80
    
