---
apiVersion: v1
kind: Service
metadata:
  name: session
  labels:
    name: session
    layer: client
    app.kubernetes.io/name: session
spec:
  selector:
    name: session
    layer: client
    app.kubernetes.io/name: session
  ports:
  - port: 6379
    name: redis
