---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session
  labels:
    name: session
    layer: client
    app.kubernetes.io/name: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
      app.kubernetes.io/name: session
  template:
    metadata:
      labels:
        name: session
        layer: client
        app.kubernetes.io/name: session
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: session
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
        