---
apiVersion: v1
kind: Service
metadata:
  name: storefront
  labels:
    name: storefront
    layer: client
    app.kubernetes.io/name: storefront
spec:
  selector:
    name: storefront
    layer: client
    app.kubernetes.io/name: storefront
  ports:
  - port: 80
    name: http
    targetPort: 8080