---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
    app.kubernetes.io/name: user
spec:
  selector:
    name: user
    app.kubernetes.io/name: user
  ports:
  - port: 80
    name: http
    targetPort: 3000
