---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    name: load
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load
      app.kubernetes.io/name: load
  template:
    metadata:
      labels:
        app: load
        app.kubernetes.io/name: load
    spec:
      containers:
      - name: load
        image: iad.ocir.io/oracle/ateam/mushop-load:2.1.0
        imagePullPolicy: Always
        args: ["-h", "edge", "-c", "15", "-r", "120"]
      nodeSelector:
        beta.kubernetes.io/os: linux
