#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: catalogue-oadb-wallet-binding
spec:
  instanceRef:
    name: catalogue-db
  parametersFrom:
    - secretKeyRef:
        name: catalogue-oadb-connection
        key: oadb_wallet_pw