name: Build and Publish Artifacts

on:
  push:
    branches:
      - main
    paths:
      - terraform/VERSION
  workflow_dispatch:

jobs:
  build_and_publish_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          docker buildx create --name multibuilder
          docker buildx use multibuilder
      - name: Build image
        run: |
          docker buildx build --pull --rm --load -t mushop-basic -f Dockerfile .
      - name: Generate Artifact
        run: |
          docker run -v $PWD:/transfer --rm --entrypoint cp mushop-basic:latest /package/mushop-basic.tar.xz /transfer/terraform/scripts/mushop-basic.tar.xz
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mushop-basic.tar.xz
          path: terraform/scripts/mushop-basic.tar.xz
  tag_and_release_note:
    runs-on: ubuntu-latest
    needs: [build_and_publish_artifact]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/tag_and_release_note.yaml
