name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          This issue is stale because it has been open 14 days with no
          activity. Remove stale label or comment or this will be closed
          in 10 days.
        stale-pr-message: >
          Marking this PR stale since there has been no activity for 14
          days. It will be closed if there is no activity for another
          10 days.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'enhancement,awaiting-approval,work-in-progress'
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
        close-issue-message: 'This issue have been closed for no activity in 25 days'
        close-pr-message: 'This PR have been closed for no activity in 25 days'
        days-before-stale: 14
        days-before-close: 10
        