name: Generate Tag and Release Note

on:
  push:
    branches:
      - main
    paths:
      - terraform/VERSION
  workflow_call:

jobs:
  tag_and_release_note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Release Noteを作成する対象のTagを取得する
      - name: Get tag
        run: |
          echo VERSION=`cat terraform/VERSION` >> $GITHUB_ENV
      - run: |
          git tag ${{ env.VERSION }}
      - run: |
          git push origin ${{ env.VERSION }}

      - name: Get artifact
        run: |
          wget \
            -O /tmp/mushop-basic.tar.xz \
            https://nightly.link/oracle-japan/oci-quest/workflows/build.yaml/main/mushop-basic.tar.xz.zip
      - name: Generate release note
        run: |
          echo RELEASE_ID=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/oracle-japan/oci-quest/releases \
            -d '{"tag_name": "${{ env.VERSION }}", "target_commitish": "main","name": "${{ env.VERSION }}", "body": "Automatic release", "draft":false, "prerelease":false, "generate_release_notes":false}' \
            | jq -r '.id') >> $GITHUB_ENV
      - name: Upload assets
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/oracle-japan/oci-quest/releases/${{ env.RELEASE_ID }}/assets?name=mushop-basic.tar.xz" \
            --data-binary "@/tmp/mushop-basic.tar.xz"
